-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Kayttajan_askare CASCADE;
DROP TABLE IF EXISTS Tarkeysluokka CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS Askareen_luokka CASCADE;